config/routes.rb
Rails.application.routes.draw do

  resources :sessions do
    resources :projects
  end

  resources :projects, only: [:show, :update] do
    get :edit_form, on: :member
    resources :scores, only: [:create]
  end
  
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :session
  has_many :scores, dependent: :destroy

  def avg_effort_score
    score = scores.map { |score| score.effort_score }.sum.to_f / scores.count || 0
    return score.nan? ? 0 : score
  end

  def avg_impact_score
    score = scores.map { |score| score.impact_score }.sum.to_f / scores.count || 0
    return score.nan? ? 0 : score
  end

  def voter_uuids
    scores.map { |score| score.uuid }
  end

  def votes_by_voter
    scores.reduce({}) do |hash, score|
      hash[score.uuid] = { name: score.username, effort_score: score.effort_score, impact_score: score.impact_score }
      hash
    end.to_json
  end

  after_create_commit { broadcast_append_to self.session, :projects }
  after_update_commit { broadcast_replace_to self.session, :projects }
  after_destroy_commit { broadcast_remove_to self.session, :projects }
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :project

  validates_presence_of :effort_score, :impact_score

  after_create_commit { project.touch }
  after_update_commit { project.touch }
end

app/models/session.rb
class Session < ApplicationRecord

  has_many :projects, dependent: :destroy

  before_create :generate_slug

  def generate_slug
    self.slug = SecureRandom.hex(10)
  end

  after_update_commit { broadcast_replace }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def create
    @session = Session.find(params[:session_id])
    @project = @session.projects.build(project_params)
    
    unless @project.name.blank?
      @project.save
    end
  end

  def edit_form
    @project = Project.find(params[:id])
    respond_to do |format|
      format.turbo_stream
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.update!(project_params)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
 
  def create
    @project = Project.find(params[:project_id])
    @score = @project.scores.find_by(uuid: score_params[:uuid])
    
    if @score
      @score.update!(score_params)
    else
      @score = @project.scores.create!(score_params)
    end
  end

  def score_params
    params.require(:score).permit(:impact_score, :effort_score, :username, :uuid)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @session = Session.create!(session_params)
    @project = Project.create!(session: @session, name: "First Project")
    
    redirect_to session_path(@session.slug)
  end

  def show
    @session = Session.find_by(slug: params[:id])
    @project = Project.new(session: @session)
    @projects = @session.projects.order(created_at: :asc).includes(:scores)

    @current_project = @projects.first
  end

  def update
    @session = Session.find(params[:id])
    @session.update!(session_params)
  end

  def session_params
    params.require(:session).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-white">
  <div class="max-w-7xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
    <div class="mt-8 flex justify-center space-x-6">
      <a href="https://www.twitter.com/marcus_orochena" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Twitter</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      </a>
      <a href="https://www.github.com/morochena/psquare" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pSquare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column h-100">
    <header class="bg-teal-600">
      <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" aria-label="Top" data-controller="user">
        <div class="w-full py-6 flex items-center justify-between border-b border-teal-500 lg:border-none">
          <div class="flex items-center">
            <a href="/">
              <span class="sr-only">Workflow</span>
              <h4 class="text-2xl font-extrabold text-white">pSquare</h4>
            </a>
            <div class="hidden ml-10 space-x-8 lg:block">
              <a href="/" class="text-base font-medium text-white hover:text-teal-50"> Home </a>
            </div>
          </div>
          <div class="ml-10 space-x-4">
            <a class="inline-block bg-teal-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75" id="nav-username"></a>
          </div>
        </div>
        <div class="py-4 flex flex-wrap justify-center space-x-6 lg:hidden">
          <a href="/" class="text-base font-medium text-white hover:text-teal-50"> Home </a>
        </div>
      </nav>
    </header>
    <main class="mx-auto mt-10 flex">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/modals/_edit_project_modal.html.erb
<!-- Main modal -->
<div id="project-edit-modal" aria-hidden="true" style="background: rgba(0,0,0,0.6)" class="hidden overflow-x-hidden overflow-y-auto fixed h-modal md:h-full top-4 left-0 right-0 md:inset-0 z-50 justify-center items-center">
  <div class="relative w-full max-w-md px-4 h-full md:h-auto">
    <!-- Modal content -->
    <div class="bg-white rounded-lg shadow relative dark:bg-gray-700">
      <div class="flex justify-end p-2">
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-action="click->edit-project#closeModal">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
      <div id="edit-project-form"></div>
    </div>
  </div>
</div>

app/views/modals/_edit_user_modal.html.erb
<div data-controller="user-set" id="user-edit-modal" aria-hidden="true" style="background: rgba(0,0,0,0.6)" class="hidden overflow-x-hidden overflow-y-auto fixed h-modal md:h-full top-4 left-0 right-0 md:inset-0 z-50 justify-center items-center">
  <div class="relative w-full max-w-md px-4 h-full md:h-auto">
    <div class="bg-white rounded-lg shadow relative dark:bg-gray-700">
      <div class="flex justify-end p-2">
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-toggle="user-edit-modal">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
      <div class="space-y-6 px-6 lg:px-8 pb-4 sm:pb-6 xl:pb-8">
        <div class="form-control">
          <h5 class="text-sm font-medium text-gray-900 block mb-2 dark:text-gray-300">Set Username</h5>
          <input data-user-set-target="username" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-teal-500 focus:border-teal-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" />
        </div>
        <div class="flex">
          <button type="button" class="text-white mx-2 bg-teal-700 hover:bg-teal-800 focus:ring-4 focus:ring-teal-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-teal-600 dark:hover:bg-teal-700 dark:focus:ring-teal-800" data-action="click->user-set#save">Save</button>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="w-full">
  <div class="relative overflow-hidden">
    <main class="relative">
      <!-- section one -->
      <div class="mt-16 mx-auto max-w-7xl px-4 sm:mt-24 sm:px-6">
        <div class="text-center">
          <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block">Do the right thing by prioritizing effectively</span>
          </h1>
          <p class="mt-3 max-w-md mx-auto text-base text-gray-500 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">pSquare allows you to rank projects by effort and impact, and then prioritize them in a way that is easy to understand.</p>
        </div>
      </div>
      <div class="text-center py-12">
        <%= form_with(model: Session.new, :method => :post) do |f| %>
          <%= f.text_field :name, placeholder: 'Session Name', required: true, class: "w-full px-5 py-3 placeholder-gray-500 focus:ring-teal-500 focus:border-teal-500 sm:max-w-xs border-gray-300 rounded-md" %>
          <%= f.submit 'Create a Session', class: "inline-block bg-teal-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75" %>
        <% end %>
      </div>
    </main>
    <div class="relative">
      <div class="absolute inset-0 flex flex-col" aria-hidden="true">
        <div class="flex-1"></div>
        <div class="flex-1 w-full bg-gray-800">
        </div>
      </div>
      <div class="max-w-3xl mx-auto px-4 sm:px-6">
        <%= image_tag 'pm-image.png', class: "relative rounded-lg object-cover" %>
      </div>
    </div>
  </div>
  <div class="bg-gray-800">
    <h1 class="text-center font-bold text-white text-4xl py-10">How to Use</h1>
    <div class="flow-root max-w-2xl mx-auto px-4 sm:pb-24 sm:px-6 lg:px-8">
      <ul role="list" class="-mb-8">
        <li>
          <div class="relative pb-8">
            <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
            <div class="relative flex space-x-3">
              <div>
                <span class="h-8 w-8 mt-3 rounded-full bg-teal-500 flex items-center justify-center ring-4 ring-white text-white">
                  1
                </span>
              </div>
              <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                <div>
                  <p class="ml-2 text-white font-bold">Create a session</p>
                  <p class="ml-2 text-sm text-white">To create a session, simply enter a name and click the above button.</p>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="relative pb-8">
            <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
            <div class="relative flex space-x-3">
              <div>
                <span class="h-8 w-8 mt-3 rounded-full bg-teal-500 flex items-center justify-center ring-4 ring-white text-white">
                  2
                </span>
              </div>
              <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                <div>
                  <p class="ml-2 text-white font-bold">Add projects</p>
                  <p class="ml-2 text-sm text-white">Add projects, features, or stories to your session on the right side of the page.</p>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="relative pb-8">
            <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
            <div class="relative flex space-x-3">
              <div>
                <span class="h-8 w-8 mt-3 rounded-full bg-teal-500 flex items-center justify-center ring-4 ring-white text-white">
                  3
                </span>
              </div>
              <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                <div>
                  <p class="ml-2 text-white font-bold">Score each project</p>
                  <p class="ml-2 text-sm text-white">Select the first project and vote on it based on effort and impact. </p>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="relative pb-8">
            <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
            <div class="relative flex space-x-3">
              <div>
                <span class="h-8 w-8 mt-3 rounded-full bg-teal-500 flex items-center justify-center ring-4 ring-white text-white">
                  4
                </span>
              </div>
              <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                <div>
                  <p class="ml-2 text-white font-bold">View project priority</p>
                  <p class="ml-2 text-sm text-white">Once voted on, the project will be plotted on the chart.</p>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="relative pb-8">
            <div class="relative flex space-x-3">
              <div>
                <span class="h-8 w-8 mt-3 rounded-full bg-teal-500 flex items-center justify-center ring-4 ring-white text-white">
                  5
                </span>
              </div>
              <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                <div>
                  <p class="ml-2 text-white font-bold">Optional: Collaborate</p>
                  <p class="ml-2 text-sm text-white">Share the session URL with peers and as they vote on projects, scores will be averaged.</p>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: [@session, @project], data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset'}) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group mt-4">
    <%= form.text_field :name, class: "shadow-sm focus:ring-teal-500 focus:border-teal-500 block w-full sm:text-sm border-gray-300 rounded-md", placeholder: 'New Project', required: true %>
  </div>
</br>
<div class="actions">
  <%= form.submit class: "inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500", 'data-reset-form-target': 'button' %>
</div>
<% end %>

app/views/projects/_project.html.erb
<li 
  class="p-list-item rounded-md" 
  id="<%= "project_#{project.id}" %>" 
  data-action="click->project#select"
  data-chart-target="projects"
  data-project-target="projects"
  data-project-id-param="<%= project.id %>"
  data-single-project-id-value="<%= project.id %>"
  data-project-name-param="<%= project.name %>"
  data-project-voters-param="<%= project.voter_uuids %>"
  data-project-votes-value="<%= project.votes_by_voter %>"
  data-project-avg-effort-score-param="<%= project.avg_effort_score %>"
  data-project-avg-impact-score-param="<%= project.avg_impact_score %>"
  data-controller="toggle-form single-project"
  >
  <div class="text-gray-600 group flex items-center px-3 py-2 text-sm font-medium rounded-md">
    <span class="truncate"> <%= project.name %></span>
    <button data-toggle-form-target="text" class="bg-gray-100 text-gray-600 group-hover:bg-gray-200 ml-auto inline-block py-0.5 px-3 text-xs rounded-full" type="button" data-edit-project-id-param="<%= project.id %>" data-action="click->edit-project#selectProject">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
      </svg>
    </button>
  </div>
</li>

app/views/projects/edit_form.turbo_stream.erb
<%= turbo_stream.update "edit-project-form" do %>
  <%= form_with(model: @project, data: { toggle_form_target: "form", action: "submit->edit-project#closeModal" }, html: { class: "space-y-6 px-6 lg:px-8 pb-4 sm:pb-6 xl:pb-8" } ) do |f| %>
    <h3 class="text-xl font-medium text-gray-900 dark:text-white">Edit Project</h3>
    <div class="form-control">
      <%= f.label :name, class: "text-sm font-medium text-gray-900 block mb-2 dark:text-gray-300" %>
      <%= f.text_field :name, required: true, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-teal-500 focus:border-teal-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>
    </div>
    <div class="flex">
      <%= f.submit "Save", class: "w-full text-white mx-2 bg-teal-700 hover:bg-teal-800 focus:ring-4 focus:ring-teal-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-teal-600 dark:hover:bg-teal-700 dark:focus:ring-teal-800" %>
    </div>
  <% end %>
  <div class="flex flex-col items-center pb-6">
    <%= link_to 'Delete', session_project_path(@project.session, @project), class: "text-red-700 hover:underline dark:text-red-500", data: {:confirm => 'Are you sure?', action: "click->edit-project#closeModal"}, :method => :delete %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div 
  data-scores-project="<%= score.project.id %>">
  data-scores-impact="<%= score.impact_score %>">
  data-scores-effort="<%= score.effort_score %>">
  data-scores-uuid="<%= score.uuid %>">
</div>